{
 "title": "Kademlia Exporter",
 "description": "Analysing DHTs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kademlia_exporter_nodes_seen_within, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kademlia_exporter_nodes_seen_within{last_seen_within=\"12h\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Number of unique nodes seen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Within last 3h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kademlia_exporter_nodes_seen_within{instance=~\"$instance\", last_seen_within=\"3h\" }) by (dht)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Unique nodes over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kademlia_exporter_nodes_seen_within{instance=~\"$instance\"}) by (dht, last_seen_within)",
     "legendFormat": "last seen within {{last_seen_within}}"
    }
   ]
  },
  { "title": "Node uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "# nodes up since",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(kademlia_exporter_nodes_seen_within{instance=~\"$instance\"}) by (dht, last_seen_within))",
     "legendFormat": "{{up_since}}"
    }
   ]
  },
  {
   "title": "Top 10 countries by # of nodes within 12h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(kademlia_exporter_nodes_seen_within{instance=~\"$instance\", last_seen_within=\"12h\", country!=\"unknown\"}) by (country))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 cloud providers by # of nodes within 12h",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(kademlia_exporter_nodes_seen_within{instance=~\"$instance\", last_seen_within=\"12h\", cloud_provider!=\"unknown\"}) by (cloud_provider))",
       "legendFormat": "{{cloud_provider}}"
      }
     ]
    }
   ]
  }
 ]
}