{
 "title": "Kademlia Exporter (libp2p)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(libp2p_identify_sent_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently established",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "libp2p_swarm_connections_established_total{instance=~\"$instance\"} - libp2p_swarm_connections_closed_total{instance=~\"$instance\"}",
       "legendFormat": "{{role}} {{protocols}}"
      }
     ]
    },
    {
     "title": "New connections per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(libp2p_swarm_connections_established_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{role}} {{protocols}}"
      }
     ]
    },
    {
     "title": "Time to establish 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, protocols) (rate(libp2p_swarm_connections_establishment_duration_bucket{instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming error per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(libp2p_swarm_connections_incoming_error_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kademlia Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of peers in routing table",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Added\"} - ignoring(action) libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Evicted\"} or ignoring(__name__, action) libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Added\"})"
      }
     ]
    },
    {
     "title": "# of nodes per kbucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Added\"} - ignoring(action) libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Evicted\"} or ignoring(__name__, action) libp2p_kad_routing_updated_total{instance=~\"$instance\", action=\"Added\"}",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Number of inbound requests per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libp2p_kad_inbound_requests_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Outbound query results",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libp2p_kad_query_result_get_closest_peers_ok_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetClosestPeers ok"
      },
      {
       "expr": "rate(libp2p_kad_query_result_get_closest_peers_error_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetClosestPeers error"
      },
      {
       "expr": "rate(libp2p_kad_query_result_get_providers_ok_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetProviders ok"
      },
      {
       "expr": "rate(libp2p_kad_query_result_get_providers_error_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetProviders error"
      },
      {
       "expr": "rate(libp2p_kad_query_result_get_record_ok_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetRecord ok"
      },
      {
       "expr": "rate(libp2p_kad_query_result_get_record_error_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "GetRecord error"
      }
     ]
    },
    {
     "title": "Outbound query duration 95th percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_kad_query_result_duration_seconds_bucket{instance=~\"$instance\"}\n[$__rate_interval])) by (le, type))",
       "legendFormat": "95th {{type}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(libp2p_kad_query_result_duration_seconds_bucket{instance=~\"$instance\"}\n[$__rate_interval])) by (le, type))",
       "legendFormat": "median {{type}}"
      }
     ]
    },
    {
     "title": "Number of requests per query 95th percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_kad_query_result_num_requests_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "num_requests {{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_kad_query_result_num_success_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "num_success {{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_kad_query_result_num_failure_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "num_failure {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Identify Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of connected nodes supporting a specific protocol",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libp2p_identify_protocols{instance=~\"$instance\"}",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Number of listen addresses reported per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_identify_received_info_listen_addrs_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "0.95-quantile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(libp2p_identify_received_info_listen_addrs_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "0.50-quantile"
      }
     ]
    },
    {
     "title": "Number of protocols reported per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_identify_received_info_protocols_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "0.95-quantile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(libp2p_identify_received_info_protocols_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "0.50-quantile"
      }
     ]
    }
   ]
  },
  {
   "title": "Ping Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping round trip time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(libp2p_ping_rtt_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(libp2p_ping_rtt_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "median"
      }
     ]
    }
   ]
  }
 ]
}