{
 "title": "Ursa Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Ursa Network\n---\n[![badge](https://img.shields.io/badge/website-000?style=for-the-badge)](https://fleek.network)&nbsp;\n[![badge](https://img.shields.io/badge/discord-333?style=for-the-badge)](https://discord.gg/fleekxyz)&nbsp;\n[![badge](https://img.shields.io/badge/twitter-666?style=for-the-badge)](https://twitter.com/fleek_net)&nbsp;\n[![badge](https://img.shields.io/badge/github-999?style=for-the-badge)](https://github.com/fleek-network)&nbsp;\n---"
   }
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "geomap",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "count by(geohash, instance) (swarm_connected_peers)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "count(up > 0)", "legendFormat": "Node Count" }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Response Time",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "rpc_response_duration{} != 0", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Ping RTT (In Seconds)",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "ping_rtt{} < 5", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Connection Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Peers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "swarm_connected_peers{}", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Connections Per Protocol",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "avg by(protocol) (identify_supported_protocols)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection Established Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by(job, role) (rate(swarm_connections_established[$__rate_interval]))",
       "legendFormat": "{{job}} ({{role}})"
      }
     ]
    },
    {
     "title": "Dial Attempt Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by(job) (rate(swarm_dial_attempt{}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Incoming Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum by(job) (rate(swarm_connections_incoming{}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Dial Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by(job) (rate(swarm_outgoing_connection_error[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Incoming Connection Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum by(job) (rate(swarm_connections_incoming_error[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitswap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bitswap Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "bitswap_sent_block_bytes{}", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Bitswap Bytes Received ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      { "expr": "bitswap_received_block_bytes{}", "legendFormat": "{{id}}" }
     ]
    }
   ]
  },
  {
   "title": "Global Relay Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay Circuits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(relay_circuit_req_accepted[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Reservation Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "rate(relay_reservation_req_accepted{}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}