version: '3'

services: 
  # Proxy to ipfs
  nginx:
    image: nginx:latest
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - ursa
    volumes:
      - ./data/prom:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  ursa:
    build:
      context: ../../.
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      # HTTP server / GraphQL API
      - "4069:4069"
    expose:
      # 4069 TCP, used by the HTTP based JSON RPC API
      # 6009 TCP and UDP, used by the P2P protocol running the network
      - 4069
      - 6009
    volumes:
      - ../../test_db:/app/ursa_db:rw
