version: '3'

services: 
  # Proxy to ipfs
  nginx:
    image: nginx:latest
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  nginxexporter:
    image: fish/nginx-exporter
    command:
    - '-nginx.scrape_uri=http://nginx:80/stub_status'
    ports:
    - '9113:9113'


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - ursa
    volumes:
      - ./data/prom:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.7.2
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000

  ursa:
    build:
      context: ../../.
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      # 6009 TCP and UDP, used by the P2P protocol running the network
      - "6009:6009"
    expose:
      # 4069 TCP, used by the HTTP based JSON RPC API
      - "4069"
      - "4070"
    volumes:
      - ../../test_db:/app/ursa_db:rw
