# fly.toml file generated for ursa-ipfs on 2022-04-28T14:41:43+03:00

app = "ursa-ipfs"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ipfs/go-ipfs:latest"

[mounts]
  source="ipfs_data"
  destination="/data/ipfs"

[env]
  DATA="/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["ipfs"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 4001
  protocol = "tcp"
  
  [[services.ports]]
    port = "4001"
