#cloud-config
groups:
  - ubuntu: [root,sys]

runcmd:
  - cd /root
  - ufw allow 80
  - ufw allow 443
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - systemctl start docker
  - systemctl enable docker
  - apt-get install -y build-essential clang ocl-icd-opencl-dev
  - git clone https://github.com/fleek-network/ursa
  - cd ursa/
  - cd docker/global-metrics/
  - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml up -d
  - cp ../full-node/init-letsencrypt.sh .
  - chmod +x ./init-letsencrypt.sh
  - EMAIL="ops@fleek.network" DOMAINS="dashboard.ursa.earth" ./init-letsencrypt.sh y
