#cloud-config
groups:
  - ubuntu: [root,sys]

runcmd:
  - apt-get install -y build-essential geoipupdate
  - |
    echo "
    AccountID ${maxmind_account}
    LicenseKey ${maxmind_key}
    EditionIDs GeoLite2-ASN GeoLite2-City GeoLite2-Country
    " > /etc/GeoIP.conf
  - geoipupdate -v
  - cd /root && git clone https://github.com/fleek-network/ursa
  - cd ursa/docker/global-metrics/
  - docker compose up -d
  - cp ../full-node/init-letsencrypt.sh .
  - chmod +x ./init-letsencrypt.sh
  - sed -i 's/docker-compose/docker compose/g' init-letsencrypt.sh
  - sed -i 's/ursa.earth/${domain}/g' data/nginx/app.conf
  - EMAIL="major@fleek.network" DOMAINS="dashboard.${domain}" ./init-letsencrypt.sh y

