#cloud-config
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnuMLreK14AhniBXXsBdtnqY2ZX+A5Nki5OSTWlmkBq3Kx/V5sGnxKzpeLjwiYO3LT/iWoxC+MYxGW5CkvnfO+YkytocZ10y3uGSsxwFJgkWKVib0nrbH2kwcB1IkUmDTMPYrOg6HzXPSdA6hF2i0Vu59KHWNKZ/5eTXoml8Xu1izEiQ0Sb4jHLwaM8++Ho4piMx5Vh2Ls7Lo6c9QyqK6dOq/o0fYAgnndd0kQ+s/TPDdsp0AKRG+lE5v5xguaojS+meGO955eGnaxBhkARHSJnMIhnCmYr0adHFK2Nz4/aqU7coyRpPTHfATjU0kHdAaWtb5zzo8EFUMavBImyQxFO84GYgbBcbclFzirCOLt1lgW3+oSuHQis3qEOcaq85YrdiKE1qlZ+HjY1a0eCMGL/kjrfhx7oLVWz3/5kxQmjCA5u2yl+TBJvalrAKUe2+oiVYjarR1qHBB0UOioHsnMBvk0CecyKWqUdCqwYq+2/dFn67GX29cqYFyf3zLqeb8= mahmoud@fleek.co

runcmd:
  - cd ~
  - ufw allow 80
  - ufw allow 443
  - echo "IPINFO_TOKEN=${ipinfo_token}" >> ~/.profile
  - source ~/.profile
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - apt-get install -y build-essential clang ocl-icd-opencl-dev
  - git clone https://github.com/fleek-network/ursa
  - cd ursa/
  - git checkout feat/global-metrics
  - cd infra/global-metrics/
  - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml up -d
  - chmod +x ./init-letsencrypt.sh
  - ./init-letsencrypt.sh
