#cloud-config
groups:
  - ubuntu: [root,sys]

runcmd:
  - cd /root
  - ufw allow 80
  - ufw allow 443
  - echo "IPINFO_TOKEN=${ipinfo_token}" >> /etc/environment
  - source /etc/environment
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - apt-get install -y build-essential clang ocl-icd-opencl-dev
  - git clone https://github.com/fleek-network/ursa
  - cd ursa/
  - cd infra/global-metrics/
  - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml up -d
  - chmod +x ./init-letsencrypt.sh
  - ./init-letsencrypt.sh
