[workspace]
members = [
  "cli",
  "network",
  "store",
  "rpc-server",
  "rpc-client",
  "service-metrics",
  ]

exclude = [
  "infra",
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[patch.crates-io]
ipld_blockstore = { git = "https://github.com/b0xtch/blockstore" }
