[workspace]
members = [
  "crates/ursa",
  "crates/ursa-gateway",
  "crates/ursa-metrics",
  "crates/ursa-network",
  "crates/ursa-rpc-client",
  "crates/ursa-rpc-server",
  "crates/ursa-store",
]

exclude = [
  "infra",
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[patch.crates-io]
ipld_blockstore = { git = "https://github.com/b0xtch/blockstore" }