FROM rust:latest as builder
ARG PROFILE=release
WORKDIR /builder

RUN apt-get update && apt-get install -y \
    clang \
    cmake \
    libclang-dev \
    protobuf-compiler

COPY . .
ENV RUST_BACKTRACE=1

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/builder/target \
    cargo build --profile $PROFILE --bin ursa-proxy \
    && mv /builder/target/release/ursa-proxy /builder

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    curl \
    && apt-get clean \
    && apt-get purge -y \
    && rm -rf /var/lib/apt/lists*

# Get compiled binaries from builder's cargo install directory
COPY --from=builder /builder/ursa-proxy /usr/local/bin

ENTRYPOINT ["ursa-proxy", "daemon"]
