FROM rust:1.61.0 AS builder

# Install dependencies
WORKDIR /usr/src/app
# RUN apt-get update && apt-get install --no-install-recommends -y build-essential clang
RUN apt-get update && apt-get install -y \
    clang \
    libclang-dev

# Make a fake Rust app to keep a cached layer of compiled crates
RUN USER=root cargo new app

# Copy the whole project
COPY . .

ENV RUST_BACKTRACE=1

# Needs at least a main.rs file with a main function
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN apt-get install -y cmake

# Install + build the actual binaries
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/src/app/target \
    make install


# Runtime image
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    && apt-get clean \
    && apt-get purge -y \
    && rm -rf /var/lib/apt/lists*

# Run as "app" user
RUN useradd -ms /bin/bash app

USER app
WORKDIR /app

# Get compiled binaries from builder's cargo install directory
COPY --from=builder /usr/local/cargo/bin/ursa /usr/local/bin/ursa

# run ursa node
ENTRYPOINT ["/usr/local/bin/ursa"]
