{
 "title": "Ursa Network",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Ursa Network\n---\n[![badge](https://img.shields.io/badge/website-000?style=for-the-badge)](https://fleek.network)&nbsp;\n[![badge](https://img.shields.io/badge/discord-333?style=for-the-badge)](https://discord.gg/fleekxyz)&nbsp;\n[![badge](https://img.shields.io/badge/twitter-666?style=for-the-badge)](https://twitter.com/fleek_net)&nbsp;\n[![badge](https://img.shields.io/badge/github-999?style=for-the-badge)](https://github.com/fleek-network)&nbsp;\n---"
   }
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "swarm_connected_peers{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ping RTT (In Seconds)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ping_rtt{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPC Response Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rpc_response_duration{} != 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kademlia Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kad_routing_updated{action=\"added\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kademlia KBucket Sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kad_routing_updated{action=\"added\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "swarm_connected_peers" }
   ]
  },
  {
   "title": "Connection Established Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(swarm_connections_established[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "swarm_connected_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dial Attempt Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(swarm_dial_attempt{}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Dial Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "rate(swarm_outgoing_connection_error{}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average protocol connections per node",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg by(protocol) (identify_supported_protocols)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(swarm_connections_incoming{}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Incoming Connection Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(swarm_connections_incoming_error[$__rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Bitswap Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "bitswap_sent_block_bytes{}", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Bitswap Bytes Received ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "bitswap_received_block_bytes{}", "legendFormat": "{{id}}" }
   ]
  },
  { "title": "Global Relay Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Relay Circuits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(relay_circuit_req_accepted)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Reservation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(relay_reservation_req_accepted{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}