[package]
name = "gateway"
version = "0.1.0"
edition = "2021"
authors = ["b0xtch <mahmoud@fleek.co>"]
license = "MIT"
repository = "https://github.com/Psychedelic/ursa"
description = "Ursa's proxy gateway"

[dependencies]
warp = "0.3.2"
tokio = { version = "1.18.2", features = ["full"] }