log_level = "ERROR"
maxminddb = "/usr/local/etc/GeoIP/GeoLite2-City.mmdb"

[server]
port = 443
addr = "0.0.0.0"
request_timeout = 5000 # 5s
concurrency_limit = 100000
cert_path = ".ursa/gateway/cert.pem"
key_path = ".ursa/gateway/key.pem"
stream_buf = 2000000 # 2mb

[indexer]
cid_url = "https://cid.contact/cid"
