[package]
name = "ursa-proxy"
authors = ["Miguel Guarniz <miguel@fleek.xyz>"]
description = "Ursa's proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
bincode.workspace = true
base64.workspace = true
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
cid.workspace = true
clap.workspace = true
hyper.workspace = true
hyper-tls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tokio-util.workspace = true
bytes.workspace = true
