[package]
name = "ursa-store"
version = "0.1.0"
edition = "2021"
authors = ["b0xtch <mahmoud@fleek.co>"]
license = "MIT"
repository = "https://github.com/Psychedelic/ursa"
description = "Ursa's store implementation"

[dependencies]
tracing = "0.1.37"
async-trait = "0.1.57"
simple_logger = "2.3.0"
ipld_blockstore = "0.1.1"
libipld = "0.14.0"
tokio = { version = "1.21.2", features = ["full"] }
db = { package = "forest_db", version = "0.1", git = "https://github.com/theBeardA/forest-rocksdb", branch = "main", features = ["rocksdb"] }

[dependencies.libp2p-bitswap]
version = "0.22.0"
git = "https://github.com/b0xtch/libp2p-bitswap"
rev = "a3779ea242816770433d37e77a69ac3afa3ce491"

[features]
default = ["rocksdb"]
rocksdb = ["db/rocksdb", "ipld_blockstore/rocksdb"]
