apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-{{ .Values.lets_encrypt_env }}
spec:
 acme:
   # The ACME server URL
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: {{ .Values.lets_enrypt_email }}
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-letsencrypt-{{ .Values.lets_encrypt_env }}
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-{{ .Values.lets_encrypt_env }}
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: {{ .Values.lets_enrypt_email }}
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-{{ .Values.lets_encrypt_env }}
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx