name = "data-transfer"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "data-transfer"
instances = { min = 2, max = 30, default = 5 }
