[metadata]
  name = "pull"

[global]
  plan = "ursa/data-transfer"
  case = "pull"
  builder = "docker:generic"
  runner = "local:docker"
  concurrent_builds = 1

[[groups]]
  id = "groups1"
  instances = { count = 10 }
  [groups.build_config.build_args]
    BINARY_NAME = 'pull'
