[metadata]
  name = "rust-cross-versions-{{ $.Env.GitReference }}"

[global]
  plan = "ursa/data-transfer"
  case = "data-transfer"
  builder = "docker:generic"
  runner = "local:docker"
  concurrent_builds = 1

[[groups]]
  id = "data-transfer"
  instances = { count = 3 }
  [groups.build_config.build_args]
    BINARY_NAME = 'data-transfer'
