name = "fetching"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "fetching"
instances = { min = 2, max = 30, default = 5 }
