version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/cache:/cache:rw
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
    depends_on:
      - certbot

  nginxexporter:
    image: fish/nginx-exporter
    command:
    - '-nginx.scrape_uri=http://nginx:80/stub_status'
    expose:
      - 9113
    depends_on:
      - nginx

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    expose: 
      - "9090"
    volumes:
      - ./data/prom:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - ursa
      - node-exporter

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - prometheus
    user: "$UID:$GID"
    entrypoint: "bash /var/lib/grafana/run.sh"

  ursa:
    # default image name which matches suggested docker run version for cache
    image: ursa
    build:
      context: ../../.
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "6009:6009"
    expose:
      # 4069 TCP, used for HTTP RPC, REST, and metrics
      - "4069"
      # 6009 TCP and UDP, used by the P2P protocol running the network
      - "6009"
    volumes:
      - ${HOME}/.ursa/:/root/.ursa/:rw
