condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
imports_granularity = 'Crate'
imports_layout = 'HorizontalVertical'
match_arm_blocks = false
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
