[package]
name = "rpc-client"
version = "0.1.0"
edition = "2021"
authors = ["b0xtch <mahmoud@fleek.co>"]
license = "MIT"
repository = "https://github.com/Psychedelic/ursa"
description = "Ursa's libp2p implementation"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
