# Ghost action to avoid pr requirements when there are no source file modifications
name: docker-build-push
on:
  pull_request:
    paths-ignore:
      - "crates/**"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"
      - ".github/workflows/docker-publish.yml"
jobs:
  build:
    name: Docker build and publish ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]
    steps:
      run: echo "No rust or workflow modifications, skipped!"
