# Ghost rust action to avoid pr requirements when there are no source file modifications
name: rust-ci
on:
  pull_request:
    paths-ignore:
      - "crates/**"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"
      - ".github/workflows/docker-publish.yml"

jobs:
  tests:
    if: '! github.event.pull_request.draft'
    name: Matrix tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: stable,           os: ubuntu-latest }
          - { rust: stable,           os: macos-latest }
          # - { rust: stable,           os: windows-latest }
          - { rust: beta,             os: ubuntu-latest }
          - { rust: nightly,          os: ubuntu-latest }
    steps:
      - run: echo "No rust or workflow modifications, skipped!"

  clippy:
    if: '! github.event.pull_request.draft'
    name: Lint with clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable ]
    steps:
      - run: echo "No rust or workflow modifications, skipped!"

  coverage:
    if: '! github.event.pull_request.draft'
    name: Tests coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ nightly ]
    steps:
      - run: echo "No rust or workflow modifications, skipped!"

  rustfmt:
    if: '! github.event.pull_request.draft'
    name: Code formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable ]
    steps:
      - run: echo "No rust or workflow modifications, skipped!"
