[metadata]
  name = "rust-cross-versions-{{ $.Env.GitReference }}"

[global]
  plan = "ursa/replication"
  case = "replication"
  builder = "docker:generic"
  runner = "local:docker"
  concurrent_builds = 1

[[groups]]
  id = "replication"
  instances = { count = 3 }
  [groups.build_config.build_args]
    BINARY_NAME = 'replication'
